apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: backend
          image: gcrのイメージ
          ports:
            - containerPort: 7000
        - name: frontend
          image: nextjsのGCRイメージ
          command:
            - 'npm run build'
          ports:
            - containerPort: 3000
      volumes:
        - name: frontend-build
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: deployment
  ports:
    - name: 'http-port'
      protocol: 'TCP'
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: sample.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nodeport
          servicePort: 80
