apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: backend
          image: gcr.io/gihyo-kube-295605/fastapi
          ports:
            - containerPort: 7000
        - name: frontend
          image: gcr.io/gihyo-kube-295605/nextjs
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: deployment
  ports:
    - name: 'http-port'
      protocol: 'TCP'
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hoge
spec:
  backend:
    serviceName: nodeport
    servicePort: 80
