name: Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    container:
      image: node:15.2.1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build Image
        env:
          HOST_NAME: ${{ secrets.HOST_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GCR_REGISTRY: ${{ secrets.GCR_REGISTRY }}
          GCR_REPOSITORY: ${{ secrets.GCR_REPOSITORY }}
        run: |
          docker build -t 
      - name: Push Image